### ISSUE TITLE
显示效果优化

### ISSUE THREAD

**Issue by OpaqueGlass** [OpaqueGlass/listChildDocs#32]
- 挂件内
  - [x] 1、扩大点击区域时，悬停在文字上不变色；
  - [x] 2、悬停在链接上时，显示鼠标为手型；扩大点击区域时，悬停`<li>`鼠标显示为手型；
- 文档内
  - [x] 3、`1.1.URL`改为无序列表（不使用全角空格缩进），并提供代码片段做显示优化（代码片段仅适用于`daylight`等主题）；
      
      ```css
      
      .list[custom-list-format*=standard-ol-on-ul][data-subtype="u"] .protyle-action {
            display: none !important;
            border: 0;
      }
        
      .protyle-wysiwyg [custom-list-format*=standard-ol-on-ul][data-subtype="u"] [data-node-id].li>[data-node-id] {
          margin-left: 5px !important;
      }
      
      .protyle-wysiwyg [custom-list-format*=standard-ol-on-ul][data-subtype="u"]  [data-node-id] {
          margin-top: 0px;
          margin-bottom: 1px;
          padding-top: 0px;
          padding-bottom: 0px;
      }
      
      .protyle-wysiwyg [custom-list-format*=standard-ol-on-ul][data-subtype="u"] .li {
          min-height: 30px;
      }
      
      .protyle-wysiwyg  [custom-list-format*=standard-ol-on-ul][data-subtype="u"] [data-node-id].li:before {
          content: "";
          position: absolute;
          height: calc(100% - 35px);
          border-left: 0.5px solid var(--b3-theme-background-light);
          top: 30px;
          left: 15px;
      }
      ```
